# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
- name: DOCKER_BUILDKIT
  value: 1

pool:
  name: Test-Pool
  tag: '$(Build.BuildId)'


steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '18.13.0'
  

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'docker-connection'
    repository: 'ravikanchan2004/testdocker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

